# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_delete_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
