# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_comment_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
