# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
